### ISSUE TITLE
C API 

### ISSUE THREAD

**Issue by c1ngular** [xiongziliang/ZLMediaKit#163]
wonderful project , would you consider to offer C API for this framework, so people could port it to other languages with minimal effort, Python/go/... make community bigger and stronger .

like Qt and FFMPEG , accessible via various of bindings , PyQt/GoQt/...

**Comment by xiongziliang** [comment]
I provided the [C interface](https://github.com/xiongziliang/ZLMediaKit/tree/3.0/c_wrapper/src) before, but I didn't maintain it later.
Now I have provided  the Android [JNI interface](https://github.com/xiongziliang/ZLMediaKit/blob/master/Android/app/src/main/cpp/native-lib.cpp),you can refer to this to implement the C interface.

I think I have time to get a C interface library later, but it depends on my schedule.

**Comment by xiongziliang** [comment]
I have now provided the C interface：
https://github.com/xiongziliang/ZLMediaKit/tree/master/api

**Comment by c1ngular** [comment]
thanks , i will give a try

**Comment by c1ngular** [comment]
took a quick scan , nice job .
i am guessing there will be more methods/interfaces exported later ?

1. a get started ReadME/documentation would be nice
2. a sample project/snippet would even be better  
3. consider change common.h/common.cpp naming to something like base.h/base.cpp or init.h/init.cpp, make it self-explanatory . 

i am still studying your framework , since i am not experienced in media streaming/processing , i will try to make a golang binding as soon as i get a solid grasp of your work .

**Comment by cyrusbehr** [comment]
Agree, would be appreciated to have a readme or some working examples which demonstrate how to use the C API.

**Comment by xiongziliang** [comment]
In fact, there are two c sdk test examples ：https://github.com/xiongziliang/ZLMediaKit/tree/master/api/tests.

Since the header file comments are very detailed, I didn't write a separate document。

The header notes are in Chinese may not be friendly to non Chinese users, so I suggest you use Google translation.
As a matter of fact, it's very troublesome for us Chinese to read English annotation codes. Some annotations also need to use translation software. In fact, I reply you in English with using translation software now.  I am sorry for my poor English。
