### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [xiongziliang/ZLMediaKit#224]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [AACEncoder](https://github.com/xiongziliang/ZLMediaKit/blob/6d3d0272a69ba06e358497112e7d00bf3d18f5bc/src/Codec/AACEncoder.cpp#L54 "Destructor for AACEncoder")
- [AMFValue::destroy](https://github.com/xiongziliang/ZLMediaKit/blob/8ae9f561108209e789ef239c4f443af8fefaf5bd/src/Rtmp/amf.cpp#L37 "AMFValue::destroy function")
- [H264Encoder](https://github.com/xiongziliang/ZLMediaKit/blob/6d3d0272a69ba06e358497112e7d00bf3d18f5bc/src/Codec/H264Encoder.cpp#L40 "Destructor for H264Encoder")

**Comment by xiongziliang** [comment]
Hello, thank you very much for your advice. I'm on vacation, so I'll reply you now,
I've checked all the suggestions you mentioned. If it's not in a destructor, it's still necessary to check the null pointer. At present, this code runs well. Deleting the redundant null pointer will not improve the performance, but deleting the code may cause unnecessary irritation, so I plan not to modify the code temporarily,thak you!

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by xiongziliang** [comment]
I agree with you very much about dangling pointer. At present, I also try to use smart pointer to avoid using raw pointer. Because some of the codes in zlmediakit have a long history, some of them are not very elegant but without bug, Some unimportant points or details don't need to be paid much attention to. Although it's very simple to modify the code, it's very troublesome to test the code. To be honest, I think it's possible to introduce bugs into the proposed changes...
